## Advanced Data Wrangling with Pandas and Numpy

## Table of Contents
* Importing the Dataset
* Checks for missing values
* Handle missing values
* Converted to date data type
* Group By and Merge Functions
* Reshape the dataset
* Save the dataset

In [6]:
## Importing the necessary libraries
import pandas as pd
import numpy as np

In [7]:
# importing the dataset
transactions = pd.read_csv("C:/Users/ADMIN/OneDrive/Documents/AI-ACCELERATOR_PROGRAM/03_labs/week_02/NumPy & Pandas/nigerian_market_transactions_1000.csv")
prices = pd.read_csv("C:/Users/ADMIN/OneDrive/Documents/AI-ACCELERATOR_PROGRAM/03_labs/week_02/NumPy & Pandas/nigerian_weekly_product_prices_1000.csv")

In [8]:
# dataset showcase
transactions.head()

,transaction_id,transaction_date,market,state,product,category,quantity,unit_price,total_amount,vendor
0,TXN0001,2024/01/24,Balogun,Lagos,Rice 50kg,Grains,5.0,78006.0,390030.0,Alhaji Musa
1,TXN0002,2024/01/17,Bodija,Oyo,Rice 50kg,Grains,1.0,76767.0,76767.0,Mama Ngozi
2,TXN0003,NaN,Bodija,Oyo,Beans brown,Grains,10.0,7127.0,71270.0,Mama Ngozi
3,TXN0004,2024-01-25,Bodija,Oyo,Garri white,Grains,5.0,2673.0,13365.0,Mr Ade
4,TXN0005,2024/01/02,Balogun,Lagos,Garri white,Grains,5.0,6345.0,31725.0,Alhaji Musa

In [9]:
prices.head()

        product category  market week_start_date  avg_price
0  Palm Oil 25l      Oil  Ogbete      2024-01-15    34397.0
1     Rice 50KG   Grains    Wuse      2024-01-29    78517.0
2  Palm Oil 25L      Oil    Wuse      2024-01-08    33591.0
3   Beans Brown   Grains  Bodija      2024-02-05     3157.0
4     Rice 50kg   Grains    Wuse      2024-02-19    75891.0

In [10]:
# checking for missing values
transactions.isnull().sum()

transaction_id        0
transaction_date     97
market                0
state                 0
product               0
category              0
quantity            211
unit_price           62
total_amount        262
vendor                0
dtype: int64

In [11]:
# checking for missing values in relative the overall data
(transactions.isnull().sum()/len(transactions))*100

transaction_id       0.0
transaction_date     9.7
market               0.0
state                0.0
product              0.0
category             0.0
quantity            21.1
unit_price           6.2
total_amount        26.2
vendor               0.0
dtype: float64

In [12]:
# checking for the missing values in prices df
prices.isnull().sum()

product             0
category            0
market              0
week_start_date     0
avg_price          99
dtype: int64

In [13]:
(prices.isnull().sum()/len(prices))*100

product            0.0
category           0.0
market             0.0
week_start_date    0.0
avg_price          9.9
dtype: float64

In [14]:
# checks for data types
prices.dtypes

product             object
category            object
market              object
week_start_date     object
avg_price          float64
dtype: object

In [15]:
transactions.dtypes

transaction_id       object
transaction_date     object
market               object
state                object
product              object
category             object
quantity            float64
unit_price          float64
total_amount        float64
vendor               object
dtype: object

In [16]:
transactions.isnull().sum()

transaction_id        0
transaction_date     97
market                0
state                 0
product               0
category              0
quantity            211
unit_price           62
total_amount        262
vendor                0
dtype: int64

In [17]:
# dropping off the total amount column
transactions.drop(columns = ["total_amount"], inplace=True)

In [18]:
# derive the total amount
transactions["total_amount"] = transactions["unit_price"]*transactions["quantity"]

In [19]:
transactions.isnull().sum()

transaction_id        0
transaction_date     97
market                0
state                 0
product               0
category              0
quantity            211
unit_price           62
vendor                0
total_amount        262
dtype: int64

In [20]:
# Handling missing values
transactions["quantity"] = transactions["quantity"].fillna(transactions["quantity"].median())
transactions["unit_price"] = transactions["unit_price"].fillna(transactions["unit_price"].median())
transactions["total_amount"] = transactions["total_amount"].fillna(transactions["total_amount"].median())

In [ ]:
# replicate missing values handling for prices

In [21]:
prices.isnull().sum()

product             0
category            0
market              0
week_start_date     0
avg_price          99
dtype: int64

In [22]:
prices["avg_price"] = prices["avg_price"].fillna(prices["avg_price"].median())

In [23]:
# Converting the date columns to actual datetime format
transactions["transaction_date"]=pd.to_datetime(transactions["transaction_date"], errors = 'coerce')
prices["week_start_date"]=pd.to_datetime(prices["week_start_date"], errors= 'coerce' )

In [24]:
transactions.dtypes

transaction_id              object
transaction_date    datetime64[ns]
market                      object
state                       object
product                     object
category                    object
quantity                   float64
unit_price                 float64
vendor                      object
total_amount               float64
dtype: object

In [25]:
transactions.duplicated().sum()

np.int64(0)

In [26]:
prices.duplicated().sum()

np.int64(21)

In [27]:
prices.drop_duplicates()

          product category   market week_start_date  avg_price
0    Palm Oil 25l      Oil   Ogbete      2024-01-15    34397.0
1       Rice 50KG   Grains     Wuse      2024-01-29    78517.0
2    Palm Oil 25L      Oil     Wuse      2024-01-08    33591.0
3     Beans Brown   Grains   Bodija      2024-02-05     3157.0
4       Rice 50kg   Grains     Wuse      2024-02-19    75891.0
..            ...      ...      ...             ...        ...
995  Palm Oil 25L      Oil  Balogun      2024-02-05    33980.0
996  Palm Oil 25l      Oil  Balogun      2024-02-26    33745.0
997   Garri white   Grains   Bodija      2024-02-26     2546.0
998   Beans Brown   Grains   Bodija      2024-01-22     4099.0
999  Palm Oil 25L      Oil   Bodija      2024-02-12    33536.0

[979 rows x 5 columns]

# Group By Function

In [28]:
# Group by state and calculate statistics
category_summary = prices.groupby('category').agg({
    'avg_price': ['mean']
})

In [29]:
print(category_summary)

             avg_price
                  mean
category
Grains    30101.813673
Oil       35546.039370

In [31]:
# Group prices dataframe by category and calculate statistics

In [32]:
category_summary = transactions.groupby('category').agg({
    'unit_price': ['mean'],
    'quantity': 'sum',
    'product': 'count'
})

In [33]:
print(category_summary)

            unit_price quantity product
                  mean      sum   count
category
Grains    31264.820194   3415.0     723
Oil       36150.797834   1242.0     277

## Merging Dataset

In [34]:
# Inner join: Sales data with market information
merged_data = pd.merge(transactions, prices, on = "market", how= "inner")

In [35]:
merged_data.head()

,transaction_id,transaction_date,market,state,product_x,category_x,quantity,unit_price,vendor,total_amount,product_y,category_y,week_start_date,avg_price
0,TXN0001,2024-01-24,Balogun,Lagos,Rice 50kg,Grains,5.0,78006.0,Alhaji Musa,390030.0,Rice 50kg,Grains,2024-02-12,77152.0
1,TXN0001,2024-01-24,Balogun,Lagos,Rice 50kg,Grains,5.0,78006.0,Alhaji Musa,390030.0,Rice 50kg,Grains,2024-02-05,77074.0
2,TXN0001,2024-01-24,Balogun,Lagos,Rice 50kg,Grains,5.0,78006.0,Alhaji Musa,390030.0,Garri white,Grains,2024-02-12,2642.0
3,TXN0001,2024-01-24,Balogun,Lagos,Rice 50kg,Grains,5.0,78006.0,Alhaji Musa,390030.0,Beans brown,Grains,2024-01-22,6699.0
4,TXN0001,2024-01-24,Balogun,Lagos,Rice 50kg,Grains,5.0,78006.0,Alhaji Musa,390030.0,Beans Brown,Grains,2024-01-15,6554.0

In [36]:
pivot = merged_data.pivot_table(
    values='total_amount',
    index='state',
    columns='market',
    aggfunc='mean')

In [37]:
print(pivot)

market        Balogun         Bodija         Ogbete           Wuse
state
Abuja             NaN            NaN            NaN  154151.295547
Enugu             NaN            NaN  116528.913223            NaN
Lagos   103600.177165            NaN            NaN            NaN
Oyo               NaN  112781.354086            NaN            NaN

In [38]:
merged_data.to_csv("merged_data.csv", index=False)